#version 450

layout(set=0 , binding = 0) buffer Input {
    uint[] numbers;
};

layout(set=0 , binding = 1) buffer Output {
    uint[] collatz;
};

uint collatz_iterations(uint n) {
    uint i = 0;
    while(n != 1) {
        if (mod(n, 2) == 0) {
            n = n / 2;
        }
        else {
            n = (3 * n) + 1;
        }
        i++;
    }
    return i;
}


void main() {
    uint index = gl_GlobalInvocationID.x;
    collatz[index] = collatz_iterations(numbers[index]);
}

